

# This file was *autogenerated* from the file src/mvp/ag_enc_id.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1461501624496790265145448589920785493717258890819 = Integer(1461501624496790265145448589920785493717258890819); _sage_const_1461501624496790265145447380994971188499300027613 = Integer(1461501624496790265145447380994971188499300027613); _sage_const_1208925814305217958863207 = Integer(1208925814305217958863207); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_20 = Integer(20); _sage_const_22222 = Integer(22222)# there must be Setup, KeyGen, Extract, Encrypt, Decrypt functions of AgEncID protocol
import numpy as np

class PublicParamethers:
    def __init__(self, p, ord, t, E, G, alpha, param, n):
        self.p = p
        self.ord = ord
        self.t = t
        self.E = E
        self.G = G
        self.ord = E.order()
        self.alpha = alpha
        self.param = param
        self.n = n
    
# def Setup(lambda_: int, n: int) -> None:
def Setup(l: int, n: int) -> PublicParamethers:
    p = _sage_const_1461501624496790265145448589920785493717258890819 
    ord = _sage_const_1461501624496790265145447380994971188499300027613 
    t = _sage_const_1208925814305217958863207 

    E = EllipticCurve(GF(p), [_sage_const_0 ,_sage_const_3 ])
    G = E([_sage_const_1 , _sage_const_2 ])

    alpha = randint(_sage_const_2 ,p)

    Temp = G

    param = np.empty(
        (_sage_const_2  * n),
        dtype=sage.schemes.elliptic_curves.ell_point.EllipticCurvePoint_finite_field
    )
    for i in range(_sage_const_0 , n):
        Temp = alpha * Temp
        param[i] = Temp

    Temp = alpha * Temp
    for i in range(n+_sage_const_1 , _sage_const_2 *n):
        Temp = alpha * Temp
        param[i] = Temp

    pp = PublicParamethers(
        p=p,
        ord=ord,
        t=t,
        E=E,
        G=G,
        alpha=alpha,
        param=param,
        n=n
    )
    return pp

def KeyGen(pp: PublicParamethers):
    gamma = randint(_sage_const_2 , pp.p)
    msk = gamma
    v = gamma * pp.G

    keyset = np.empty(
        (pp.n),
        dtype=sage.schemes.elliptic_curves.ell_point.EllipticCurvePoint_finite_field
    )
    for i in range(_sage_const_0 , pp.n):
        keyset[i] = gamma * pp.param[i]
    
    return msk, v, keyset

def Extract(pp: PublicParamethers, S: list[int]):
    K_S = _sage_const_0 
    for j in S:
        K_S += pp.param[pp.n - j]

    return K_S

def Encrypt(pp: PublicParamethers, S: list[int], v, m):
    t = randint(_sage_const_2 , pp.p)

    K_S = Extract(pp, S)

    c1 = t * pp.G
    c2 = t * (v + K_S)
    c3 = m * pp.param[pp.n - _sage_const_1 ].weil_pairing(t * pp.param[_sage_const_0 ], pp.ord)

    return c1, c2, c3

def main():
    pp = Setup(l=None, n=_sage_const_20 )
    msk, v, keyset = KeyGen(pp)
    # K_S = Extract(pp, [i for i in range(2, 20)])
    S = [i for i in range(_sage_const_2 , _sage_const_20 )]
    m = _sage_const_22222 
    c1, c2, c3 = Encrypt(pp, S, v, m)
    print(c1, c2, c3)

if __name__ == "__main__":
    main()

