

# This file was *autogenerated* from the file src/mvp/ag_enc_id.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_123456787654321 = Integer(123456787654321); _sage_const_10 = Integer(10); _sage_const_100 = Integer(100)# there must be Setup, KeyGen, Extract, Encrypt, Decrypt functions of AgEncID protocol
import time
import hashlib

import numpy as np

load('src/mvp/bn381.sage')

def Hash(number: int, p: int):
    number_bytes = number.to_bytes((number.bit_length() + _sage_const_7 ) // _sage_const_8 , byteorder='big')

    sha3_384_hash = hashlib.sha3_384(number_bytes).hexdigest()

    return int(sha3_384_hash, _sage_const_16 ) % p
    
def Setup(l: int, m: int):
    pairing = BN381Pairing()
    
    gamma = randint(_sage_const_1 , pairing.p)

    G = pairing.P1
    H = pairing.P2

    # Change P1 to random generator
    msk = (G, gamma)
    pk = [gamma * G, pairing.e(G, H)]
    temp = _sage_const_0 
    for i in range(m):
        temp += H
        pk.append(temp)

    return msk, pk

def KeyGen(pp):
    gamma = randint(_sage_const_2 , pp.p)
    msk = gamma
    v = gamma * pp.G

    keyset = np.empty(
        (pp.n),
        dtype=sage.schemes.elliptic_curves.ell_point.EllipticCurvePoint_finite_field
    )
    for i in range(_sage_const_0 , pp.n):
        keyset[i] = gamma * pp.param[i]
    
    return msk, v, keyset

def Extract(pp, S: list[int]):
    K_S = _sage_const_0 
    for j in S:
        K_S += pp.param[pp.n - j]

    return K_S

def Encrypt(pp, S: list[int], v, m):
    t = randint(_sage_const_2 , pp.p)

    K_S = Extract(pp, S)

    c1 = t * pp.G
    c2 = t * (v + K_S)
    c3 = m * pp.param[pp.n - _sage_const_1 ].weil_pairing(t * pp.param[_sage_const_0 ], pp.ord)

    return c1, c2, c3

def Decrypt(pp, S: list[int], i: int, d_i, C):
    c1, c2, c3 = C

    b_iS = _sage_const_0 
    for j in S:
        if j != i:
            b_iS += pp.param[pp.n - j + i]

    top = (d_i + b_iS).weil_pairing(c1, pp.ord)
    down = pp.param[i].weil_pairing(c2, pp.ord)

    return c3 * (top / down)

def time_evalation(n: int):
    time_start = time.time()
    pp = Setup(l=None, n=n)
    time_finish = time.time()
    print(f"Setup time: {time_finish - time_start:0.3f} s.")

    time_start = time.time()
    msk, v, keyset = KeyGen(pp)
    time_finish = time.time()
    print(f"KeyGen time: {time_finish - time_start:0.3f} s.")

    S = [i for i in range(_sage_const_2 , pp.n)]
    m = _sage_const_123456787654321 
    time_start = time.time()
    C = Encrypt(pp, S, v, m)
    time_finish = time.time()
    print(f"Encrypt time: {time_finish - time_start:0.3f} s.")

    i = _sage_const_10 
    time_start = time.time()
    m_ = Decrypt(pp, S, i, keyset[i], C)
    time_finish = time.time()
    print(f"Decrypt time: {time_finish - time_start:0.3f} s.")

    print("m: ", m)
    print("m':", m_)

def main(m: int):
    msk, pk = Setup(l=None, m=m)

    # msk, v, keyset = KeyGen(pp)

    # S = [i for i in range(2, pp.n)]
    # m = 123456787654321
    # C = Encrypt(pp, S, v, m)

    # i = 10
    # m_ = Decrypt(pp, S, i, keyset[i], C)

    # print("m: ", m)
    # print("m':", m_)

if __name__ == "__main__":
    main(_sage_const_100 )
    # time_evalation(100)

