[package]
name = "relative_implementation"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-std = "0.5.0"
ark-test-curves = {version = "0.5.0", features = ["bls12_381_curve"] }
